/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "rtl/alu_16.v:2" *)
module ALU(X, Y, Z, Sign, Carry, Zero, Parity, Overflow);
  (* src = "rtl/alu_16.v:5" *)
  output Carry;
  (* src = "rtl/alu_16.v:5" *)
  output Overflow;
  (* src = "rtl/alu_16.v:5" *)
  output Parity;
  (* src = "rtl/alu_16.v:5" *)
  output Sign;
  (* src = "rtl/alu_16.v:3" *)
  input [15:0] X;
  (* src = "rtl/alu_16.v:3" *)
  input [15:0] Y;
  (* src = "rtl/alu_16.v:4" *)
  output [15:0] Z;
  (* src = "rtl/alu_16.v:5" *)
  output Zero;
  assign Carry = 1'hx;
  assign Overflow = 1'h0;
  assign Parity = 1'hx;
  assign Sign = 1'hx;
  assign Z = 16'hxxxx;
  assign Zero = 1'hx;
endmodule
