/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "rtl/counter.v:2" *)
module counter(clk, rst, count);
  (* src = "rtl/counter.v:7" *)
  wire [3:0] _00_;
  wire _01_;
  wire _02_;
  (* src = "rtl/counter.v:3" *)
  input clk;
  (* src = "rtl/counter.v:5" *)
  output [3:0] count;
  reg [3:0] count;
  (* src = "rtl/counter.v:4" *)
  input rst;
  assign _00_[1] = count[0] ^ count[1];
  assign _01_ = ~(count[0] & count[1]);
  assign _00_[2] = ~(_01_ ^ count[2]);
  assign _02_ = count[2] & ~(_01_);
  assign _00_[3] = _02_ ^ count[3];
  assign _00_[0] = ~count[0];
  (* src = "rtl/counter.v:7" *)
  always @(negedge clk or posedge rst)
    if (rst)
      count[0] <= 0;
    else
      count[0] <= _00_[0];
  (* src = "rtl/counter.v:7" *)
  always @(negedge clk or posedge rst)
    if (rst)
      count[1] <= 0;
    else
      count[1] <= _00_[1];
  (* src = "rtl/counter.v:7" *)
  always @(negedge clk or posedge rst)
    if (rst)
      count[2] <= 0;
    else
      count[2] <= _00_[2];
  (* src = "rtl/counter.v:7" *)
  always @(negedge clk or posedge rst)
    if (rst)
      count[3] <= 0;
    else
      count[3] <= _00_[3];
endmodule
