/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "rtl/cyclic_lamp.v:1" *)
module cyclic_lamp(clock, light);
  (* src = "rtl/cyclic_lamp.v:2" *)
  input clock;
  (* src = "rtl/cyclic_lamp.v:3" *)
  output [2:0] light;
  (* onehot = 32'd1 *)
  reg [2:0] state;
  assign light[2] = ~(state[2] | state[1]);
  assign light[0] = state[1] & ~(light[2]);
  assign light[1] = state[2] & ~(light[2]);
  always @(posedge clock)
      state[0] <= state[1];
  always @(posedge clock)
      state[1] <= state[2];
  always @(posedge clock)
      state[2] <= state[0];
endmodule
