/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "rtl/decoder2x4.v:23" *)
module decoder2x4(in, out);
  (* src = "rtl/decoder2x4.v:24" *)
  input [1:0] in;
  (* src = "rtl/decoder2x4.v:25" *)
  output [3:0] out;
  assign out[0] = ~(in[1] | in[0]);
  assign out[1] = in[0] & ~(in[1]);
  assign out[2] = in[1] & ~(in[0]);
  assign out[3] = in[1] & in[0];
endmodule
