/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "rtl/demux1x4.v:23" *)
module demux1x4(a, sel, o0, o1, o2, o3);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  (* src = "rtl/demux1x4.v:24" *)
  input [3:0] a;
  (* src = "rtl/demux1x4.v:26" *)
  output o0;
  (* src = "rtl/demux1x4.v:26" *)
  output o1;
  (* src = "rtl/demux1x4.v:26" *)
  output o2;
  (* src = "rtl/demux1x4.v:26" *)
  output o3;
  (* src = "rtl/demux1x4.v:25" *)
  input [1:0] sel;
  assign _00_ = sel[0] | ~(sel[1]);
  assign o2 = a[2] & ~(_00_);
  assign _01_ = sel[1] | sel[0];
  assign o0 = a[0] & ~(_01_);
  assign _02_ = sel[1] | ~(sel[0]);
  assign o1 = a[1] & ~(_02_);
  assign _03_ = ~(sel[1] & sel[0]);
  assign o3 = a[3] & ~(_03_);
endmodule
