/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "rtl/dff.v:1" *)
module dff(D, clk, Q, Q_bar);
  (* src = "rtl/dff.v:4" *)
  wire _0_;
  (* src = "rtl/dff.v:2" *)
  input D;
  (* src = "rtl/dff.v:3" *)
  output Q;
  reg Q;
  (* src = "rtl/dff.v:3" *)
  output Q_bar;
  reg Q_bar;
  (* src = "rtl/dff.v:2" *)
  input clk;
  assign _0_ = ~D;
  (* src = "rtl/dff.v:4" *)
  always @(negedge clk)
      Q_bar <= _0_;
  (* src = "rtl/dff.v:4" *)
  always @(negedge clk)
      Q <= D;
endmodule
