/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "rtl/encoder4x2.v:23" *)
module encoder4x2(d, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  (* src = "rtl/encoder4x2.v:24" *)
  input [3:0] d;
  (* src = "rtl/encoder4x2.v:25" *)
  output [1:0] out;
  assign _05_ = d[1] | d[0];
  assign _06_ = d[2] | ~(d[3]);
  assign _07_ = d[0] | ~(d[1]);
  assign _00_ = d[3] | d[2];
  assign _01_ = _00_ | _07_;
  assign _02_ = d[3] | ~(d[2]);
  assign out[0] = ~((_06_ | _05_) & _01_);
  assign _03_ = ~((_02_ & _06_) | _05_);
  assign _04_ = _01_ & ~(_03_);
  assign out[1] = _03_ & ~(_04_);
endmodule
