/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* src = "rtl/evm.v:1" *)
module buttonControl(clk, reset, button, valid_vote);
  (* src = "rtl/evm.v:10" *)
  wire [30:0] _000_;
  (* src = "rtl/evm.v:22" *)
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  (* src = "rtl/evm.v:4" *)
  input button;
  (* src = "rtl/evm.v:2" *)
  input clk;
  (* src = "rtl/evm.v:8" *)
  reg [30:0] counter;
  (* src = "rtl/evm.v:3" *)
  input reset;
  (* src = "rtl/evm.v:5" *)
  output valid_vote;
  reg valid_vote;
  assign _183_ = ~reset;
  assign _184_ = counter[0] | ~(counter[1]);
  assign _185_ = counter[2] | ~(counter[3]);
  assign _186_ = ~(_185_ | _184_);
  assign _187_ = ~(counter[5] | counter[4]);
  assign _188_ = counter[7] | counter[6];
  assign _189_ = _187_ & ~(_188_);
  assign _190_ = ~(_189_ & _186_);
  assign _191_ = counter[9] | counter[8];
  assign _192_ = counter[11] | counter[10];
  assign _193_ = _192_ | _191_;
  assign _194_ = counter[13] | counter[12];
  assign _195_ = counter[15] | counter[14];
  assign _196_ = _195_ | _194_;
  assign _197_ = _196_ | _193_;
  assign _198_ = _197_ | _190_;
  assign _199_ = counter[17] | counter[16];
  assign _200_ = counter[19] | counter[18];
  assign _201_ = _200_ | _199_;
  assign _202_ = counter[21] | counter[20];
  assign _203_ = counter[23] | counter[22];
  assign _204_ = _203_ | _202_;
  assign _205_ = _204_ | _201_;
  assign _206_ = counter[25] | counter[24];
  assign _207_ = counter[27] | counter[26];
  assign _208_ = _207_ | _206_;
  assign _209_ = counter[29] | counter[28];
  assign _210_ = _209_ | counter[30];
  assign _211_ = _210_ | _208_;
  assign _212_ = _211_ | _205_;
  assign _213_ = _212_ | _198_;
  assign _001_ = _183_ & ~(_213_);
  assign _214_ = ~(button & counter[0]);
  assign _215_ = ~counter[30];
  assign _002_ = ~counter[2];
  assign _003_ = ~counter[3];
  assign _004_ = ~((_003_ | _002_) & _189_);
  assign _005_ = _004_ | _197_;
  assign _006_ = _005_ | _205_;
  assign _007_ = _006_ | _208_;
  assign _008_ = _007_ | _209_;
  assign _009_ = _215_ & ~(_008_);
  assign _010_ = counter[30] | counter[29];
  assign _011_ = counter[28] | counter[27];
  assign _012_ = _011_ | _010_;
  assign _013_ = counter[26] | counter[25];
  assign _014_ = counter[24] | counter[23];
  assign _015_ = _014_ | _013_;
  assign _016_ = _015_ | _012_;
  assign _017_ = counter[22] | counter[21];
  assign _018_ = counter[20] | counter[19];
  assign _019_ = _018_ | _017_;
  assign _020_ = counter[18] | counter[17];
  assign _021_ = counter[16] | counter[15];
  assign _022_ = _021_ | _020_;
  assign _023_ = _022_ | _019_;
  assign _024_ = _023_ | _016_;
  assign _025_ = counter[14] | counter[13];
  assign _026_ = counter[12] | counter[11];
  assign _027_ = _026_ | _025_;
  assign _028_ = counter[10] | counter[9];
  assign _029_ = counter[8] | counter[7];
  assign _030_ = _029_ | _028_;
  assign _031_ = _030_ | _027_;
  assign _032_ = counter[6] | counter[5];
  assign _033_ = counter[4] | ~(counter[3]);
  assign _034_ = _033_ | _032_;
  assign _035_ = counter[1] & ~(counter[2]);
  assign _036_ = ~(_035_ & counter[0]);
  assign _037_ = _036_ | _034_;
  assign _038_ = _037_ | _031_;
  assign _039_ = ~((_038_ | _024_) & _009_);
  assign _040_ = _039_ | ~(button);
  assign _041_ = _040_ ? _214_ : counter[0];
  assign _000_[0] = _183_ & ~(_041_);
  assign _042_ = ~(counter[1] & button);
  assign _043_ = ~(counter[1] ^ counter[0]);
  assign _044_ = _040_ ? _042_ : _043_;
  assign _000_[1] = _183_ & ~(_044_);
  assign _045_ = ~(button & counter[2]);
  assign _046_ = counter[1] & counter[0];
  assign _047_ = _046_ ^ _002_;
  assign _048_ = _040_ ? _045_ : _047_;
  assign _000_[2] = _183_ & ~(_048_);
  assign _049_ = ~(counter[3] & button);
  assign _050_ = _046_ & ~(_002_);
  assign _051_ = _050_ ^ _003_;
  assign _052_ = _040_ ? _049_ : _051_;
  assign _000_[3] = _183_ & ~(_052_);
  assign _053_ = ~(button & counter[4]);
  assign _054_ = ~(counter[3] & counter[2]);
  assign _055_ = _046_ & ~(_054_);
  assign _056_ = ~(_055_ ^ counter[4]);
  assign _057_ = _040_ ? _053_ : _056_;
  assign _000_[4] = _183_ & ~(_057_);
  assign _058_ = ~(button & counter[5]);
  assign _059_ = ~(_055_ & counter[4]);
  assign _060_ = _059_ ^ counter[5];
  assign _061_ = _040_ ? _058_ : _060_;
  assign _000_[5] = _183_ & ~(_061_);
  assign _062_ = ~(button & counter[6]);
  assign _063_ = ~(counter[5] & counter[4]);
  assign _064_ = _055_ & ~(_063_);
  assign _065_ = ~(_064_ ^ counter[6]);
  assign _066_ = _040_ ? _062_ : _065_;
  assign _000_[6] = _183_ & ~(_066_);
  assign _067_ = ~(button & counter[7]);
  assign _068_ = ~(_064_ & counter[6]);
  assign _069_ = _068_ ^ counter[7];
  assign _070_ = _040_ ? _067_ : _069_;
  assign _000_[7] = _183_ & ~(_070_);
  assign _071_ = ~(button & counter[8]);
  assign _072_ = ~(counter[7] & counter[6]);
  assign _073_ = _072_ | _063_;
  assign _074_ = _055_ & ~(_073_);
  assign _075_ = ~(_074_ ^ counter[8]);
  assign _076_ = _040_ ? _071_ : _075_;
  assign _000_[8] = _183_ & ~(_076_);
  assign _077_ = ~(button & counter[9]);
  assign _078_ = ~(_074_ & counter[8]);
  assign _079_ = _078_ ^ counter[9];
  assign _080_ = _040_ ? _077_ : _079_;
  assign _000_[9] = _183_ & ~(_080_);
  assign _081_ = ~(button & counter[10]);
  assign _082_ = ~(counter[9] & counter[8]);
  assign _083_ = _082_ | ~(_074_);
  assign _084_ = _083_ ^ counter[10];
  assign _085_ = _040_ ? _081_ : _084_;
  assign _000_[10] = _183_ & ~(_085_);
  assign _086_ = ~(button & counter[11]);
  assign _087_ = _083_ | ~(counter[10]);
  assign _088_ = _087_ ^ counter[11];
  assign _089_ = _040_ ? _086_ : _088_;
  assign _000_[11] = _183_ & ~(_089_);
  assign _090_ = ~(button & counter[12]);
  assign _091_ = ~(counter[11] & counter[10]);
  assign _092_ = _091_ | _082_;
  assign _093_ = _074_ & ~(_092_);
  assign _094_ = ~(_093_ ^ counter[12]);
  assign _095_ = _040_ ? _090_ : _094_;
  assign _000_[12] = _183_ & ~(_095_);
  assign _096_ = ~(button & counter[13]);
  assign _097_ = ~(_093_ & counter[12]);
  assign _098_ = _097_ ^ counter[13];
  assign _099_ = _040_ ? _096_ : _098_;
  assign _000_[13] = _183_ & ~(_099_);
  assign _100_ = ~(button & counter[14]);
  assign _101_ = ~(counter[13] & counter[12]);
  assign _102_ = _101_ | ~(_093_);
  assign _103_ = _102_ ^ counter[14];
  assign _104_ = _040_ ? _100_ : _103_;
  assign _000_[14] = _183_ & ~(_104_);
  assign _105_ = ~(button & counter[15]);
  assign _106_ = _102_ | ~(counter[14]);
  assign _107_ = _106_ ^ counter[15];
  assign _108_ = _040_ ? _105_ : _107_;
  assign _000_[15] = _183_ & ~(_108_);
  assign _109_ = ~(button & counter[16]);
  assign _110_ = ~(counter[15] & counter[14]);
  assign _111_ = _110_ | _101_;
  assign _112_ = _111_ | _092_;
  assign _113_ = _074_ & ~(_112_);
  assign _114_ = ~(_113_ ^ counter[16]);
  assign _115_ = _040_ ? _109_ : _114_;
  assign _000_[16] = _183_ & ~(_115_);
  assign _116_ = ~(button & counter[17]);
  assign _117_ = ~(_113_ & counter[16]);
  assign _118_ = _117_ ^ counter[17];
  assign _119_ = _040_ ? _116_ : _118_;
  assign _000_[17] = _183_ & ~(_119_);
  assign _120_ = ~(button & counter[18]);
  assign _121_ = ~(counter[17] & counter[16]);
  assign _122_ = _121_ | ~(_113_);
  assign _123_ = _122_ ^ counter[18];
  assign _124_ = _040_ ? _120_ : _123_;
  assign _000_[18] = _183_ & ~(_124_);
  assign _125_ = ~(button & counter[19]);
  assign _126_ = _122_ | ~(counter[18]);
  assign _127_ = _126_ ^ counter[19];
  assign _128_ = _040_ ? _125_ : _127_;
  assign _000_[19] = _183_ & ~(_128_);
  assign _129_ = ~(button & counter[20]);
  assign _130_ = ~(counter[19] & counter[18]);
  assign _131_ = _130_ | _121_;
  assign _132_ = _113_ & ~(_131_);
  assign _133_ = ~(_132_ ^ counter[20]);
  assign _134_ = _040_ ? _129_ : _133_;
  assign _000_[20] = _183_ & ~(_134_);
  assign _135_ = ~(button & counter[21]);
  assign _136_ = ~(_132_ & counter[20]);
  assign _137_ = _136_ ^ counter[21];
  assign _138_ = _040_ ? _135_ : _137_;
  assign _000_[21] = _183_ & ~(_138_);
  assign _139_ = ~(button & counter[22]);
  assign _140_ = ~(counter[21] & counter[20]);
  assign _141_ = _140_ | ~(_132_);
  assign _142_ = _141_ ^ counter[22];
  assign _143_ = _040_ ? _139_ : _142_;
  assign _000_[22] = _183_ & ~(_143_);
  assign _144_ = ~(button & counter[23]);
  assign _145_ = _141_ | ~(counter[22]);
  assign _146_ = _145_ ^ counter[23];
  assign _147_ = _040_ ? _144_ : _146_;
  assign _000_[23] = _183_ & ~(_147_);
  assign _148_ = ~(button & counter[24]);
  assign _149_ = ~(counter[23] & counter[22]);
  assign _150_ = _149_ | _140_;
  assign _151_ = _150_ | _131_;
  assign _152_ = _113_ & ~(_151_);
  assign _153_ = ~(_152_ ^ counter[24]);
  assign _154_ = _040_ ? _148_ : _153_;
  assign _000_[24] = _183_ & ~(_154_);
  assign _155_ = ~(button & counter[25]);
  assign _156_ = ~(_152_ & counter[24]);
  assign _157_ = _156_ ^ counter[25];
  assign _158_ = _040_ ? _155_ : _157_;
  assign _000_[25] = _183_ & ~(_158_);
  assign _159_ = ~(button & counter[26]);
  assign _160_ = ~(counter[25] & counter[24]);
  assign _161_ = _160_ | ~(_152_);
  assign _162_ = _161_ ^ counter[26];
  assign _163_ = _040_ ? _159_ : _162_;
  assign _000_[26] = _183_ & ~(_163_);
  assign _164_ = ~(button & counter[27]);
  assign _165_ = _161_ | ~(counter[26]);
  assign _166_ = _165_ ^ counter[27];
  assign _167_ = _040_ ? _164_ : _166_;
  assign _000_[27] = _183_ & ~(_167_);
  assign _168_ = ~(button & counter[28]);
  assign _169_ = ~(counter[27] & counter[26]);
  assign _170_ = _169_ | _160_;
  assign _171_ = _152_ & ~(_170_);
  assign _172_ = ~(_171_ ^ counter[28]);
  assign _173_ = _040_ ? _168_ : _172_;
  assign _000_[28] = _183_ & ~(_173_);
  assign _174_ = ~(button & counter[29]);
  assign _175_ = ~(_171_ & counter[28]);
  assign _176_ = _175_ ^ counter[29];
  assign _177_ = _040_ ? _174_ : _176_;
  assign _000_[29] = _183_ & ~(_177_);
  assign _178_ = ~(button & counter[30]);
  assign _179_ = ~(counter[29] & counter[28]);
  assign _180_ = _171_ & ~(_179_);
  assign _181_ = _180_ ^ _215_;
  assign _182_ = _040_ ? _178_ : _181_;
  assign _000_[30] = _183_ & ~(_182_);
  (* src = "rtl/evm.v:22" *)
  always @(posedge clk)
      valid_vote <= _001_;
  (* src = "rtl/evm.v:10" *)
  always @(posedge clk)
      counter[0] <= _000_[0];
  (* src = "rtl/evm.v:10" *)
  always @(posedge clk)
      counter[1] <= _000_[1];
  (* src = "rtl/evm.v:10" *)
  always @(posedge clk)
      counter[2] <= _000_[2];
  (* src = "rtl/evm.v:10" *)
  always @(posedge clk)
      counter[3] <= _000_[3];
  (* src = "rtl/evm.v:10" *)
  always @(posedge clk)
      counter[4] <= _000_[4];
  (* src = "rtl/evm.v:10" *)
  always @(posedge clk)
      counter[5] <= _000_[5];
  (* src = "rtl/evm.v:10" *)
  always @(posedge clk)
      counter[6] <= _000_[6];
  (* src = "rtl/evm.v:10" *)
  always @(posedge clk)
      counter[7] <= _000_[7];
  (* src = "rtl/evm.v:10" *)
  always @(posedge clk)
      counter[8] <= _000_[8];
  (* src = "rtl/evm.v:10" *)
  always @(posedge clk)
      counter[9] <= _000_[9];
  (* src = "rtl/evm.v:10" *)
  always @(posedge clk)
      counter[10] <= _000_[10];
  (* src = "rtl/evm.v:10" *)
  always @(posedge clk)
      counter[11] <= _000_[11];
  (* src = "rtl/evm.v:10" *)
  always @(posedge clk)
      counter[12] <= _000_[12];
  (* src = "rtl/evm.v:10" *)
  always @(posedge clk)
      counter[13] <= _000_[13];
  (* src = "rtl/evm.v:10" *)
  always @(posedge clk)
      counter[14] <= _000_[14];
  (* src = "rtl/evm.v:10" *)
  always @(posedge clk)
      counter[15] <= _000_[15];
  (* src = "rtl/evm.v:10" *)
  always @(posedge clk)
      counter[16] <= _000_[16];
  (* src = "rtl/evm.v:10" *)
  always @(posedge clk)
      counter[17] <= _000_[17];
  (* src = "rtl/evm.v:10" *)
  always @(posedge clk)
      counter[18] <= _000_[18];
  (* src = "rtl/evm.v:10" *)
  always @(posedge clk)
      counter[19] <= _000_[19];
  (* src = "rtl/evm.v:10" *)
  always @(posedge clk)
      counter[20] <= _000_[20];
  (* src = "rtl/evm.v:10" *)
  always @(posedge clk)
      counter[21] <= _000_[21];
  (* src = "rtl/evm.v:10" *)
  always @(posedge clk)
      counter[22] <= _000_[22];
  (* src = "rtl/evm.v:10" *)
  always @(posedge clk)
      counter[23] <= _000_[23];
  (* src = "rtl/evm.v:10" *)
  always @(posedge clk)
      counter[24] <= _000_[24];
  (* src = "rtl/evm.v:10" *)
  always @(posedge clk)
      counter[25] <= _000_[25];
  (* src = "rtl/evm.v:10" *)
  always @(posedge clk)
      counter[26] <= _000_[26];
  (* src = "rtl/evm.v:10" *)
  always @(posedge clk)
      counter[27] <= _000_[27];
  (* src = "rtl/evm.v:10" *)
  always @(posedge clk)
      counter[28] <= _000_[28];
  (* src = "rtl/evm.v:10" *)
  always @(posedge clk)
      counter[29] <= _000_[29];
  (* src = "rtl/evm.v:10" *)
  always @(posedge clk)
      counter[30] <= _000_[30];
endmodule

(* src = "rtl/evm.v:35" *)
module modeControl(clk, reset, mode, valid_vote_casted, cand1_vote, cand2_vote, cand3_vote, cand4_vote, cand1_button_press, cand2_button_press, cand3_button_press, cand4_button_press, leds);
  (* src = "rtl/evm.v:53" *)
  wire [30:0] _000_;
  (* src = "rtl/evm.v:64" *)
  wire [7:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  (* src = "rtl/evm.v:44" *)
  input cand1_button_press;
  (* src = "rtl/evm.v:40" *)
  input [7:0] cand1_vote;
  (* src = "rtl/evm.v:45" *)
  input cand2_button_press;
  (* src = "rtl/evm.v:41" *)
  input [7:0] cand2_vote;
  (* src = "rtl/evm.v:46" *)
  input cand3_button_press;
  (* src = "rtl/evm.v:42" *)
  input [7:0] cand3_vote;
  (* src = "rtl/evm.v:47" *)
  input cand4_button_press;
  (* src = "rtl/evm.v:43" *)
  input [7:0] cand4_vote;
  (* src = "rtl/evm.v:36" *)
  input clk;
  (* src = "rtl/evm.v:51" *)
  reg [30:0] counter;
  (* src = "rtl/evm.v:48" *)
  output [7:0] leds;
  reg [7:0] leds;
  (* src = "rtl/evm.v:38" *)
  input mode;
  (* src = "rtl/evm.v:37" *)
  input reset;
  (* src = "rtl/evm.v:39" *)
  input valid_vote_casted;
  assign _002_ = ~mode;
  assign _003_ = counter[29] | counter[28];
  assign _004_ = counter[27] | counter[26];
  assign _005_ = counter[25] | counter[24];
  assign _006_ = _005_ | _004_;
  assign _007_ = counter[23] | counter[22];
  assign _008_ = counter[21] | counter[20];
  assign _009_ = _008_ | _007_;
  assign _010_ = counter[19] | counter[18];
  assign _011_ = counter[17] | counter[16];
  assign _012_ = _011_ | _010_;
  assign _013_ = _012_ | _009_;
  assign _014_ = counter[15] | counter[14];
  assign _015_ = counter[13] | counter[12];
  assign _016_ = _015_ | _014_;
  assign _017_ = counter[11] | counter[10];
  assign _018_ = counter[9] | counter[8];
  assign _019_ = _018_ | _017_;
  assign _020_ = _019_ | _016_;
  assign _021_ = counter[7] | counter[6];
  assign _022_ = counter[5] | counter[4];
  assign _023_ = _022_ | _021_;
  assign _024_ = counter[3] | counter[2];
  assign _025_ = counter[1] | counter[0];
  assign _026_ = _025_ | _024_;
  assign _027_ = _026_ | _023_;
  assign _028_ = _027_ | _020_;
  assign _029_ = _028_ | _013_;
  assign _030_ = _029_ | _006_;
  assign _031_ = _030_ | _003_;
  assign _032_ = ~((_031_ | counter[30]) & _002_);
  assign _033_ = cand4_button_press ? cand4_vote[0] : leds[0];
  assign _034_ = cand3_button_press ? cand3_vote[0] : _033_;
  assign _035_ = cand2_button_press ? cand2_vote[0] : _034_;
  assign _036_ = cand1_button_press ? cand1_vote[0] : _035_;
  assign _037_ = ~(_036_ & mode);
  assign _001_[0] = ~((_037_ & _032_) | reset);
  assign _038_ = cand4_button_press ? cand4_vote[1] : leds[1];
  assign _039_ = cand3_button_press ? cand3_vote[1] : _038_;
  assign _040_ = cand2_button_press ? cand2_vote[1] : _039_;
  assign _041_ = cand1_button_press ? cand1_vote[1] : _040_;
  assign _042_ = ~(_041_ & mode);
  assign _001_[1] = ~((_042_ & _032_) | reset);
  assign _043_ = cand4_button_press ? cand4_vote[2] : leds[2];
  assign _044_ = cand3_button_press ? cand3_vote[2] : _043_;
  assign _045_ = cand2_button_press ? cand2_vote[2] : _044_;
  assign _046_ = cand1_button_press ? cand1_vote[2] : _045_;
  assign _047_ = ~(_046_ & mode);
  assign _001_[2] = ~((_047_ & _032_) | reset);
  assign _048_ = cand4_button_press ? cand4_vote[3] : leds[3];
  assign _049_ = cand3_button_press ? cand3_vote[3] : _048_;
  assign _050_ = cand2_button_press ? cand2_vote[3] : _049_;
  assign _051_ = cand1_button_press ? cand1_vote[3] : _050_;
  assign _052_ = ~(_051_ & mode);
  assign _001_[3] = ~((_052_ & _032_) | reset);
  assign _053_ = cand4_button_press ? cand4_vote[4] : leds[4];
  assign _054_ = cand3_button_press ? cand3_vote[4] : _053_;
  assign _055_ = cand2_button_press ? cand2_vote[4] : _054_;
  assign _056_ = cand1_button_press ? cand1_vote[4] : _055_;
  assign _057_ = ~(_056_ & mode);
  assign _001_[4] = ~((_057_ & _032_) | reset);
  assign _058_ = cand4_button_press ? cand4_vote[5] : leds[5];
  assign _059_ = cand3_button_press ? cand3_vote[5] : _058_;
  assign _060_ = cand2_button_press ? cand2_vote[5] : _059_;
  assign _061_ = cand1_button_press ? cand1_vote[5] : _060_;
  assign _062_ = ~(_061_ & mode);
  assign _001_[5] = ~((_062_ & _032_) | reset);
  assign _063_ = cand4_button_press ? cand4_vote[6] : leds[6];
  assign _064_ = cand3_button_press ? cand3_vote[6] : _063_;
  assign _065_ = cand2_button_press ? cand2_vote[6] : _064_;
  assign _066_ = cand1_button_press ? cand1_vote[6] : _065_;
  assign _067_ = ~(_066_ & mode);
  assign _001_[6] = ~((_067_ & _032_) | reset);
  assign _068_ = cand4_button_press ? cand4_vote[7] : leds[7];
  assign _069_ = cand3_button_press ? cand3_vote[7] : _068_;
  assign _070_ = cand2_button_press ? cand2_vote[7] : _069_;
  assign _071_ = cand1_button_press ? cand1_vote[7] : _070_;
  assign _072_ = ~(_071_ & mode);
  assign _001_[7] = ~((_072_ & _032_) | reset);
  assign _073_ = ~reset;
  assign _074_ = ~counter[0];
  assign _075_ = _003_ | counter[30];
  assign _076_ = _075_ | _006_;
  assign _077_ = ~(_076_ | _013_);
  assign _078_ = _028_ | ~(_077_);
  assign _079_ = counter[1] & counter[0];
  assign _080_ = ~((_079_ | counter[2]) & counter[3]);
  assign _081_ = _023_ | ~(_080_);
  assign _082_ = _081_ | _020_;
  assign _083_ = _082_ | _013_;
  assign _084_ = _083_ | _006_;
  assign _085_ = ~(_084_ | _003_);
  assign _086_ = _085_ & ~(counter[30]);
  assign _087_ = counter[30] | counter[29];
  assign _088_ = counter[28] | counter[27];
  assign _089_ = _088_ | _087_;
  assign _090_ = counter[26] | counter[25];
  assign _091_ = counter[24] | counter[23];
  assign _092_ = _091_ | _090_;
  assign _093_ = _092_ | _089_;
  assign _094_ = counter[22] | counter[21];
  assign _095_ = counter[20] | counter[19];
  assign _096_ = _095_ | _094_;
  assign _097_ = counter[18] | counter[17];
  assign _098_ = counter[16] | counter[15];
  assign _099_ = _098_ | _097_;
  assign _100_ = _099_ | _096_;
  assign _101_ = _100_ | _093_;
  assign _102_ = counter[14] | counter[13];
  assign _103_ = counter[12] | counter[11];
  assign _104_ = _103_ | _102_;
  assign _105_ = counter[10] | counter[9];
  assign _106_ = counter[8] | counter[7];
  assign _107_ = _106_ | _105_;
  assign _108_ = _107_ | _104_;
  assign _109_ = counter[6] | counter[5];
  assign _110_ = counter[4] | ~(counter[3]);
  assign _111_ = _110_ | _109_;
  assign _112_ = counter[2] | ~(counter[1]);
  assign _113_ = _112_ | counter[0];
  assign _114_ = _113_ | _111_;
  assign _115_ = _114_ | _108_;
  assign _116_ = ~((_115_ | _101_) & _086_);
  assign _117_ = _078_ & ~(_116_);
  assign _118_ = ~((_117_ | valid_vote_casted) & _074_);
  assign _000_[0] = _073_ & ~(_118_);
  assign _119_ = counter[1] ^ counter[0];
  assign _120_ = ~((_117_ | valid_vote_casted) & _119_);
  assign _000_[1] = _073_ & ~(_120_);
  assign _121_ = _079_ ^ counter[2];
  assign _122_ = ~((_117_ | valid_vote_casted) & _121_);
  assign _000_[2] = _073_ & ~(_122_);
  assign _123_ = _079_ & counter[2];
  assign _124_ = _123_ ^ counter[3];
  assign _125_ = ~((_117_ | valid_vote_casted) & _124_);
  assign _000_[3] = _073_ & ~(_125_);
  assign _126_ = ~(counter[3] & counter[2]);
  assign _127_ = _079_ & ~(_126_);
  assign _128_ = _127_ ^ counter[4];
  assign _129_ = ~((_117_ | valid_vote_casted) & _128_);
  assign _000_[4] = _073_ & ~(_129_);
  assign _130_ = _127_ & counter[4];
  assign _131_ = _130_ ^ counter[5];
  assign _132_ = ~((_117_ | valid_vote_casted) & _131_);
  assign _000_[5] = _073_ & ~(_132_);
  assign _133_ = ~(counter[5] & counter[4]);
  assign _134_ = _127_ & ~(_133_);
  assign _135_ = _134_ ^ counter[6];
  assign _136_ = ~((_117_ | valid_vote_casted) & _135_);
  assign _000_[6] = _073_ & ~(_136_);
  assign _137_ = _134_ & counter[6];
  assign _138_ = _137_ ^ counter[7];
  assign _139_ = ~((_117_ | valid_vote_casted) & _138_);
  assign _000_[7] = _073_ & ~(_139_);
  assign _140_ = ~(counter[7] & counter[6]);
  assign _141_ = _140_ | _133_;
  assign _142_ = _127_ & ~(_141_);
  assign _143_ = _142_ ^ counter[8];
  assign _144_ = ~((_117_ | valid_vote_casted) & _143_);
  assign _000_[8] = _073_ & ~(_144_);
  assign _145_ = _142_ & counter[8];
  assign _146_ = _145_ ^ counter[9];
  assign _147_ = ~((_117_ | valid_vote_casted) & _146_);
  assign _000_[9] = _073_ & ~(_147_);
  assign _148_ = ~(counter[9] & counter[8]);
  assign _149_ = _148_ | ~(_142_);
  assign _150_ = ~(_149_ ^ counter[10]);
  assign _151_ = ~((_117_ | valid_vote_casted) & _150_);
  assign _000_[10] = _073_ & ~(_151_);
  assign _152_ = counter[10] & ~(_149_);
  assign _153_ = _152_ ^ counter[11];
  assign _154_ = ~((_117_ | valid_vote_casted) & _153_);
  assign _000_[11] = _073_ & ~(_154_);
  assign _155_ = ~(counter[11] & counter[10]);
  assign _156_ = _155_ | _148_;
  assign _157_ = _142_ & ~(_156_);
  assign _158_ = _157_ ^ counter[12];
  assign _159_ = ~((_117_ | valid_vote_casted) & _158_);
  assign _000_[12] = _073_ & ~(_159_);
  assign _160_ = _157_ & counter[12];
  assign _161_ = _160_ ^ counter[13];
  assign _162_ = ~((_117_ | valid_vote_casted) & _161_);
  assign _000_[13] = _073_ & ~(_162_);
  assign _163_ = ~(counter[13] & counter[12]);
  assign _164_ = _163_ | ~(_157_);
  assign _165_ = ~(_164_ ^ counter[14]);
  assign _166_ = ~((_117_ | valid_vote_casted) & _165_);
  assign _000_[14] = _073_ & ~(_166_);
  assign _167_ = counter[14] & ~(_164_);
  assign _168_ = _167_ ^ counter[15];
  assign _169_ = ~((_117_ | valid_vote_casted) & _168_);
  assign _000_[15] = _073_ & ~(_169_);
  assign _170_ = ~(counter[15] & counter[14]);
  assign _171_ = _170_ | _163_;
  assign _172_ = _171_ | _156_;
  assign _173_ = _142_ & ~(_172_);
  assign _174_ = _173_ ^ counter[16];
  assign _175_ = ~((_117_ | valid_vote_casted) & _174_);
  assign _000_[16] = _073_ & ~(_175_);
  assign _176_ = _173_ & counter[16];
  assign _177_ = _176_ ^ counter[17];
  assign _178_ = ~((_117_ | valid_vote_casted) & _177_);
  assign _000_[17] = _073_ & ~(_178_);
  assign _179_ = ~(counter[17] & counter[16]);
  assign _180_ = _179_ | ~(_173_);
  assign _181_ = ~(_180_ ^ counter[18]);
  assign _182_ = ~((_117_ | valid_vote_casted) & _181_);
  assign _000_[18] = _073_ & ~(_182_);
  assign _183_ = counter[18] & ~(_180_);
  assign _184_ = _183_ ^ counter[19];
  assign _185_ = ~((_117_ | valid_vote_casted) & _184_);
  assign _000_[19] = _073_ & ~(_185_);
  assign _186_ = ~(counter[19] & counter[18]);
  assign _187_ = _186_ | _179_;
  assign _188_ = _173_ & ~(_187_);
  assign _189_ = _188_ ^ counter[20];
  assign _190_ = ~((_117_ | valid_vote_casted) & _189_);
  assign _000_[20] = _073_ & ~(_190_);
  assign _191_ = _188_ & counter[20];
  assign _192_ = _191_ ^ counter[21];
  assign _193_ = ~((_117_ | valid_vote_casted) & _192_);
  assign _000_[21] = _073_ & ~(_193_);
  assign _194_ = ~(counter[21] & counter[20]);
  assign _195_ = _194_ | ~(_188_);
  assign _196_ = ~(_195_ ^ counter[22]);
  assign _197_ = ~((_117_ | valid_vote_casted) & _196_);
  assign _000_[22] = _073_ & ~(_197_);
  assign _198_ = counter[22] & ~(_195_);
  assign _199_ = _198_ ^ counter[23];
  assign _200_ = ~((_117_ | valid_vote_casted) & _199_);
  assign _000_[23] = _073_ & ~(_200_);
  assign _201_ = ~(counter[23] & counter[22]);
  assign _202_ = _201_ | _194_;
  assign _203_ = _202_ | _187_;
  assign _204_ = _173_ & ~(_203_);
  assign _205_ = _204_ ^ counter[24];
  assign _206_ = ~((_117_ | valid_vote_casted) & _205_);
  assign _000_[24] = _073_ & ~(_206_);
  assign _207_ = _204_ & counter[24];
  assign _208_ = _207_ ^ counter[25];
  assign _209_ = ~((_117_ | valid_vote_casted) & _208_);
  assign _000_[25] = _073_ & ~(_209_);
  assign _210_ = ~(counter[25] & counter[24]);
  assign _211_ = _210_ | ~(_204_);
  assign _212_ = ~(_211_ ^ counter[26]);
  assign _213_ = ~((_117_ | valid_vote_casted) & _212_);
  assign _000_[26] = _073_ & ~(_213_);
  assign _214_ = counter[26] & ~(_211_);
  assign _215_ = _214_ ^ counter[27];
  assign _216_ = ~((_117_ | valid_vote_casted) & _215_);
  assign _000_[27] = _073_ & ~(_216_);
  assign _217_ = ~(counter[27] & counter[26]);
  assign _218_ = _217_ | _210_;
  assign _219_ = _204_ & ~(_218_);
  assign _220_ = _219_ ^ counter[28];
  assign _221_ = ~((_117_ | valid_vote_casted) & _220_);
  assign _000_[28] = _073_ & ~(_221_);
  assign _222_ = _219_ & counter[28];
  assign _223_ = _222_ ^ counter[29];
  assign _224_ = ~((_117_ | valid_vote_casted) & _223_);
  assign _000_[29] = _073_ & ~(_224_);
  assign _225_ = ~(counter[29] & counter[28]);
  assign _226_ = _219_ & ~(_225_);
  assign _227_ = _226_ ^ counter[30];
  assign _228_ = ~((_117_ | valid_vote_casted) & _227_);
  assign _000_[30] = _073_ & ~(_228_);
  (* src = "rtl/evm.v:64" *)
  always @(posedge clk)
      leds[0] <= _001_[0];
  (* src = "rtl/evm.v:64" *)
  always @(posedge clk)
      leds[1] <= _001_[1];
  (* src = "rtl/evm.v:64" *)
  always @(posedge clk)
      leds[2] <= _001_[2];
  (* src = "rtl/evm.v:64" *)
  always @(posedge clk)
      leds[3] <= _001_[3];
  (* src = "rtl/evm.v:64" *)
  always @(posedge clk)
      leds[4] <= _001_[4];
  (* src = "rtl/evm.v:64" *)
  always @(posedge clk)
      leds[5] <= _001_[5];
  (* src = "rtl/evm.v:64" *)
  always @(posedge clk)
      leds[6] <= _001_[6];
  (* src = "rtl/evm.v:64" *)
  always @(posedge clk)
      leds[7] <= _001_[7];
  (* src = "rtl/evm.v:53" *)
  always @(posedge clk)
      counter[0] <= _000_[0];
  (* src = "rtl/evm.v:53" *)
  always @(posedge clk)
      counter[1] <= _000_[1];
  (* src = "rtl/evm.v:53" *)
  always @(posedge clk)
      counter[2] <= _000_[2];
  (* src = "rtl/evm.v:53" *)
  always @(posedge clk)
      counter[3] <= _000_[3];
  (* src = "rtl/evm.v:53" *)
  always @(posedge clk)
      counter[4] <= _000_[4];
  (* src = "rtl/evm.v:53" *)
  always @(posedge clk)
      counter[5] <= _000_[5];
  (* src = "rtl/evm.v:53" *)
  always @(posedge clk)
      counter[6] <= _000_[6];
  (* src = "rtl/evm.v:53" *)
  always @(posedge clk)
      counter[7] <= _000_[7];
  (* src = "rtl/evm.v:53" *)
  always @(posedge clk)
      counter[8] <= _000_[8];
  (* src = "rtl/evm.v:53" *)
  always @(posedge clk)
      counter[9] <= _000_[9];
  (* src = "rtl/evm.v:53" *)
  always @(posedge clk)
      counter[10] <= _000_[10];
  (* src = "rtl/evm.v:53" *)
  always @(posedge clk)
      counter[11] <= _000_[11];
  (* src = "rtl/evm.v:53" *)
  always @(posedge clk)
      counter[12] <= _000_[12];
  (* src = "rtl/evm.v:53" *)
  always @(posedge clk)
      counter[13] <= _000_[13];
  (* src = "rtl/evm.v:53" *)
  always @(posedge clk)
      counter[14] <= _000_[14];
  (* src = "rtl/evm.v:53" *)
  always @(posedge clk)
      counter[15] <= _000_[15];
  (* src = "rtl/evm.v:53" *)
  always @(posedge clk)
      counter[16] <= _000_[16];
  (* src = "rtl/evm.v:53" *)
  always @(posedge clk)
      counter[17] <= _000_[17];
  (* src = "rtl/evm.v:53" *)
  always @(posedge clk)
      counter[18] <= _000_[18];
  (* src = "rtl/evm.v:53" *)
  always @(posedge clk)
      counter[19] <= _000_[19];
  (* src = "rtl/evm.v:53" *)
  always @(posedge clk)
      counter[20] <= _000_[20];
  (* src = "rtl/evm.v:53" *)
  always @(posedge clk)
      counter[21] <= _000_[21];
  (* src = "rtl/evm.v:53" *)
  always @(posedge clk)
      counter[22] <= _000_[22];
  (* src = "rtl/evm.v:53" *)
  always @(posedge clk)
      counter[23] <= _000_[23];
  (* src = "rtl/evm.v:53" *)
  always @(posedge clk)
      counter[24] <= _000_[24];
  (* src = "rtl/evm.v:53" *)
  always @(posedge clk)
      counter[25] <= _000_[25];
  (* src = "rtl/evm.v:53" *)
  always @(posedge clk)
      counter[26] <= _000_[26];
  (* src = "rtl/evm.v:53" *)
  always @(posedge clk)
      counter[27] <= _000_[27];
  (* src = "rtl/evm.v:53" *)
  always @(posedge clk)
      counter[28] <= _000_[28];
  (* src = "rtl/evm.v:53" *)
  always @(posedge clk)
      counter[29] <= _000_[29];
  (* src = "rtl/evm.v:53" *)
  always @(posedge clk)
      counter[30] <= _000_[30];
endmodule

(* src = "rtl/evm.v:91" *)
module voteLogger(clk, reset, mode, cand1_vote_valid, cand2_vote_valid, cand3_vote_valid, cand4_vote_valid, cand1_vote_recvd, cand2_vote_recvd, cand3_vote_recvd, cand4_vote_recvd);
  (* src = "rtl/evm.v:105" *)
  wire [7:0] _000_;
  (* src = "rtl/evm.v:105" *)
  wire [7:0] _001_;
  (* src = "rtl/evm.v:105" *)
  wire [7:0] _002_;
  (* src = "rtl/evm.v:105" *)
  wire [7:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  (* src = "rtl/evm.v:99" *)
  output [7:0] cand1_vote_recvd;
  reg [7:0] cand1_vote_recvd;
  (* src = "rtl/evm.v:95" *)
  input cand1_vote_valid;
  (* src = "rtl/evm.v:100" *)
  output [7:0] cand2_vote_recvd;
  reg [7:0] cand2_vote_recvd;
  (* src = "rtl/evm.v:96" *)
  input cand2_vote_valid;
  (* src = "rtl/evm.v:101" *)
  output [7:0] cand3_vote_recvd;
  reg [7:0] cand3_vote_recvd;
  (* src = "rtl/evm.v:97" *)
  input cand3_vote_valid;
  (* src = "rtl/evm.v:102" *)
  output [7:0] cand4_vote_recvd;
  reg [7:0] cand4_vote_recvd;
  (* src = "rtl/evm.v:98" *)
  input cand4_vote_valid;
  (* src = "rtl/evm.v:92" *)
  input clk;
  (* src = "rtl/evm.v:94" *)
  input mode;
  (* src = "rtl/evm.v:93" *)
  input reset;
  assign _154_ = ~reset;
  assign _155_ = ~cand4_vote_recvd[0];
  assign _156_ = mode | ~(cand4_vote_valid);
  assign _157_ = _156_ ^ cand4_vote_recvd[0];
  assign _158_ = cand3_vote_valid & ~(mode);
  assign _159_ = _158_ ? _155_ : _157_;
  assign _160_ = cand2_vote_valid & ~(mode);
  assign _161_ = _160_ ? _155_ : _159_;
  assign _162_ = cand1_vote_valid & ~(mode);
  assign _163_ = _162_ ? _155_ : _161_;
  assign _003_[0] = _154_ & ~(_163_);
  assign _164_ = ~cand4_vote_recvd[1];
  assign _165_ = ~(cand4_vote_recvd[1] ^ cand4_vote_recvd[0]);
  assign _166_ = _156_ ? _164_ : _165_;
  assign _167_ = _158_ ? _164_ : _166_;
  assign _168_ = _160_ ? _164_ : _167_;
  assign _169_ = _162_ ? _164_ : _168_;
  assign _003_[1] = _154_ & ~(_169_);
  assign _170_ = ~cand4_vote_recvd[2];
  assign _171_ = ~(cand4_vote_recvd[1] & cand4_vote_recvd[0]);
  assign _172_ = _171_ ^ cand4_vote_recvd[2];
  assign _173_ = _156_ ? _170_ : _172_;
  assign _174_ = _158_ ? _170_ : _173_;
  assign _175_ = _160_ ? _170_ : _174_;
  assign _176_ = _162_ ? _170_ : _175_;
  assign _003_[2] = _154_ & ~(_176_);
  assign _177_ = ~cand4_vote_recvd[3];
  assign _178_ = cand4_vote_recvd[2] & ~(_171_);
  assign _179_ = _178_ ^ _177_;
  assign _004_ = _156_ ? _177_ : _179_;
  assign _005_ = _158_ ? _177_ : _004_;
  assign _006_ = _160_ ? _177_ : _005_;
  assign _007_ = _162_ ? _177_ : _006_;
  assign _003_[3] = _154_ & ~(_007_);
  assign _008_ = ~cand4_vote_recvd[4];
  assign _009_ = ~(cand4_vote_recvd[3] & cand4_vote_recvd[2]);
  assign _010_ = _009_ | _171_;
  assign _011_ = _010_ ^ cand4_vote_recvd[4];
  assign _012_ = _156_ ? _008_ : _011_;
  assign _013_ = _158_ ? _008_ : _012_;
  assign _014_ = _160_ ? _008_ : _013_;
  assign _015_ = _162_ ? _008_ : _014_;
  assign _003_[4] = _154_ & ~(_015_);
  assign _016_ = ~cand4_vote_recvd[5];
  assign _017_ = cand4_vote_recvd[4] & ~(_010_);
  assign _018_ = _017_ ^ _016_;
  assign _019_ = _156_ ? _016_ : _018_;
  assign _020_ = _158_ ? _016_ : _019_;
  assign _021_ = _160_ ? _016_ : _020_;
  assign _022_ = _162_ ? _016_ : _021_;
  assign _003_[5] = _154_ & ~(_022_);
  assign _023_ = ~cand4_vote_recvd[6];
  assign _024_ = ~(cand4_vote_recvd[5] & cand4_vote_recvd[4]);
  assign _025_ = _024_ | _010_;
  assign _026_ = _025_ ^ cand4_vote_recvd[6];
  assign _027_ = _156_ ? _023_ : _026_;
  assign _028_ = _158_ ? _023_ : _027_;
  assign _029_ = _160_ ? _023_ : _028_;
  assign _030_ = _162_ ? _023_ : _029_;
  assign _003_[6] = _154_ & ~(_030_);
  assign _031_ = ~cand4_vote_recvd[7];
  assign _032_ = cand4_vote_recvd[6] & ~(_025_);
  assign _033_ = _032_ ^ _031_;
  assign _034_ = _156_ ? _031_ : _033_;
  assign _035_ = _158_ ? _031_ : _034_;
  assign _036_ = _160_ ? _031_ : _035_;
  assign _037_ = _162_ ? _031_ : _036_;
  assign _003_[7] = _154_ & ~(_037_);
  assign _038_ = ~cand3_vote_recvd[0];
  assign _039_ = _158_ ^ _038_;
  assign _040_ = _160_ ? _038_ : _039_;
  assign _041_ = _162_ ? _038_ : _040_;
  assign _002_[0] = _154_ & ~(_041_);
  assign _042_ = ~cand3_vote_recvd[1];
  assign _043_ = ~(cand3_vote_recvd[1] ^ cand3_vote_recvd[0]);
  assign _044_ = _158_ ? _043_ : _042_;
  assign _045_ = _160_ ? _042_ : _044_;
  assign _046_ = _162_ ? _042_ : _045_;
  assign _002_[1] = _154_ & ~(_046_);
  assign _047_ = ~cand3_vote_recvd[2];
  assign _048_ = ~(cand3_vote_recvd[1] & cand3_vote_recvd[0]);
  assign _049_ = _048_ ^ cand3_vote_recvd[2];
  assign _050_ = _158_ ? _049_ : _047_;
  assign _051_ = _160_ ? _047_ : _050_;
  assign _052_ = _162_ ? _047_ : _051_;
  assign _002_[2] = _154_ & ~(_052_);
  assign _053_ = ~cand3_vote_recvd[3];
  assign _054_ = cand3_vote_recvd[2] & ~(_048_);
  assign _055_ = _054_ ^ _053_;
  assign _056_ = _158_ ? _055_ : _053_;
  assign _057_ = _160_ ? _053_ : _056_;
  assign _058_ = _162_ ? _053_ : _057_;
  assign _002_[3] = _154_ & ~(_058_);
  assign _059_ = ~cand3_vote_recvd[4];
  assign _060_ = ~(cand3_vote_recvd[3] & cand3_vote_recvd[2]);
  assign _061_ = _060_ | _048_;
  assign _062_ = _061_ ^ cand3_vote_recvd[4];
  assign _063_ = _158_ ? _062_ : _059_;
  assign _064_ = _160_ ? _059_ : _063_;
  assign _065_ = _162_ ? _059_ : _064_;
  assign _002_[4] = _154_ & ~(_065_);
  assign _066_ = ~cand3_vote_recvd[5];
  assign _067_ = cand3_vote_recvd[4] & ~(_061_);
  assign _068_ = _067_ ^ _066_;
  assign _069_ = _158_ ? _068_ : _066_;
  assign _070_ = _160_ ? _066_ : _069_;
  assign _071_ = _162_ ? _066_ : _070_;
  assign _002_[5] = _154_ & ~(_071_);
  assign _072_ = ~cand3_vote_recvd[6];
  assign _073_ = ~(cand3_vote_recvd[5] & cand3_vote_recvd[4]);
  assign _074_ = _073_ | _061_;
  assign _075_ = _074_ ^ cand3_vote_recvd[6];
  assign _076_ = _158_ ? _075_ : _072_;
  assign _077_ = _160_ ? _072_ : _076_;
  assign _078_ = _162_ ? _072_ : _077_;
  assign _002_[6] = _154_ & ~(_078_);
  assign _079_ = ~cand3_vote_recvd[7];
  assign _080_ = cand3_vote_recvd[6] & ~(_074_);
  assign _081_ = _080_ ^ _079_;
  assign _082_ = _158_ ? _081_ : _079_;
  assign _083_ = _160_ ? _079_ : _082_;
  assign _084_ = _162_ ? _079_ : _083_;
  assign _002_[7] = _154_ & ~(_084_);
  assign _085_ = ~cand2_vote_recvd[0];
  assign _086_ = _160_ ^ _085_;
  assign _087_ = _162_ ? _085_ : _086_;
  assign _001_[0] = _154_ & ~(_087_);
  assign _088_ = ~cand2_vote_recvd[1];
  assign _089_ = ~(cand2_vote_recvd[1] ^ cand2_vote_recvd[0]);
  assign _090_ = _160_ ? _089_ : _088_;
  assign _091_ = _162_ ? _088_ : _090_;
  assign _001_[1] = _154_ & ~(_091_);
  assign _092_ = ~cand2_vote_recvd[2];
  assign _093_ = cand2_vote_recvd[1] & cand2_vote_recvd[0];
  assign _094_ = _093_ ^ _092_;
  assign _095_ = _160_ ? _094_ : _092_;
  assign _096_ = _162_ ? _092_ : _095_;
  assign _001_[2] = _154_ & ~(_096_);
  assign _097_ = ~cand2_vote_recvd[3];
  assign _098_ = _093_ & ~(_092_);
  assign _099_ = _098_ ^ _097_;
  assign _100_ = _160_ ? _099_ : _097_;
  assign _101_ = _162_ ? _097_ : _100_;
  assign _001_[3] = _154_ & ~(_101_);
  assign _102_ = ~cand2_vote_recvd[4];
  assign _103_ = ~(cand2_vote_recvd[3] & cand2_vote_recvd[2]);
  assign _104_ = _093_ & ~(_103_);
  assign _105_ = _104_ ^ _102_;
  assign _106_ = _160_ ? _105_ : _102_;
  assign _107_ = _162_ ? _102_ : _106_;
  assign _001_[4] = _154_ & ~(_107_);
  assign _108_ = ~cand2_vote_recvd[5];
  assign _109_ = _104_ & ~(_102_);
  assign _110_ = _109_ ^ _108_;
  assign _111_ = _160_ ? _110_ : _108_;
  assign _112_ = _162_ ? _108_ : _111_;
  assign _001_[5] = _154_ & ~(_112_);
  assign _113_ = ~cand2_vote_recvd[6];
  assign _114_ = cand2_vote_recvd[5] & cand2_vote_recvd[4];
  assign _115_ = ~(_114_ & _104_);
  assign _116_ = _115_ ^ cand2_vote_recvd[6];
  assign _117_ = _160_ ? _116_ : _113_;
  assign _118_ = _162_ ? _113_ : _117_;
  assign _001_[6] = _154_ & ~(_118_);
  assign _119_ = ~cand2_vote_recvd[7];
  assign _120_ = cand2_vote_recvd[6] & ~(_115_);
  assign _121_ = _120_ ^ _119_;
  assign _122_ = _160_ ? _121_ : _119_;
  assign _123_ = _162_ ? _119_ : _122_;
  assign _001_[7] = _154_ & ~(_123_);
  assign _124_ = ~(_162_ ^ cand1_vote_recvd[0]);
  assign _000_[0] = _154_ & ~(_124_);
  assign _125_ = ~cand1_vote_recvd[1];
  assign _126_ = ~(cand1_vote_recvd[1] ^ cand1_vote_recvd[0]);
  assign _127_ = _162_ ? _126_ : _125_;
  assign _000_[1] = _154_ & ~(_127_);
  assign _128_ = ~cand1_vote_recvd[2];
  assign _129_ = cand1_vote_recvd[1] & cand1_vote_recvd[0];
  assign _130_ = _129_ ^ _128_;
  assign _131_ = _162_ ? _130_ : _128_;
  assign _000_[2] = _154_ & ~(_131_);
  assign _132_ = ~cand1_vote_recvd[3];
  assign _133_ = _129_ & ~(_128_);
  assign _134_ = _133_ ^ _132_;
  assign _135_ = _162_ ? _134_ : _132_;
  assign _000_[3] = _154_ & ~(_135_);
  assign _136_ = ~cand1_vote_recvd[4];
  assign _137_ = ~(cand1_vote_recvd[3] & cand1_vote_recvd[2]);
  assign _138_ = _129_ & ~(_137_);
  assign _139_ = _138_ ^ _136_;
  assign _140_ = _162_ ? _139_ : _136_;
  assign _000_[4] = _154_ & ~(_140_);
  assign _141_ = ~cand1_vote_recvd[5];
  assign _142_ = _138_ & ~(_136_);
  assign _143_ = _142_ ^ _141_;
  assign _144_ = _162_ ? _143_ : _141_;
  assign _000_[5] = _154_ & ~(_144_);
  assign _145_ = ~cand1_vote_recvd[6];
  assign _146_ = cand1_vote_recvd[5] & cand1_vote_recvd[4];
  assign _147_ = ~(_146_ & _138_);
  assign _148_ = _147_ ^ cand1_vote_recvd[6];
  assign _149_ = _162_ ? _148_ : _145_;
  assign _000_[6] = _154_ & ~(_149_);
  assign _150_ = ~cand1_vote_recvd[7];
  assign _151_ = cand1_vote_recvd[6] & ~(_147_);
  assign _152_ = _151_ ^ _150_;
  assign _153_ = _162_ ? _152_ : _150_;
  assign _000_[7] = _154_ & ~(_153_);
  (* src = "rtl/evm.v:105" *)
  always @(posedge clk)
      cand1_vote_recvd[0] <= _000_[0];
  (* src = "rtl/evm.v:105" *)
  always @(posedge clk)
      cand1_vote_recvd[1] <= _000_[1];
  (* src = "rtl/evm.v:105" *)
  always @(posedge clk)
      cand1_vote_recvd[2] <= _000_[2];
  (* src = "rtl/evm.v:105" *)
  always @(posedge clk)
      cand1_vote_recvd[3] <= _000_[3];
  (* src = "rtl/evm.v:105" *)
  always @(posedge clk)
      cand1_vote_recvd[4] <= _000_[4];
  (* src = "rtl/evm.v:105" *)
  always @(posedge clk)
      cand1_vote_recvd[5] <= _000_[5];
  (* src = "rtl/evm.v:105" *)
  always @(posedge clk)
      cand1_vote_recvd[6] <= _000_[6];
  (* src = "rtl/evm.v:105" *)
  always @(posedge clk)
      cand1_vote_recvd[7] <= _000_[7];
  (* src = "rtl/evm.v:105" *)
  always @(posedge clk)
      cand2_vote_recvd[0] <= _001_[0];
  (* src = "rtl/evm.v:105" *)
  always @(posedge clk)
      cand2_vote_recvd[1] <= _001_[1];
  (* src = "rtl/evm.v:105" *)
  always @(posedge clk)
      cand2_vote_recvd[2] <= _001_[2];
  (* src = "rtl/evm.v:105" *)
  always @(posedge clk)
      cand2_vote_recvd[3] <= _001_[3];
  (* src = "rtl/evm.v:105" *)
  always @(posedge clk)
      cand2_vote_recvd[4] <= _001_[4];
  (* src = "rtl/evm.v:105" *)
  always @(posedge clk)
      cand2_vote_recvd[5] <= _001_[5];
  (* src = "rtl/evm.v:105" *)
  always @(posedge clk)
      cand2_vote_recvd[6] <= _001_[6];
  (* src = "rtl/evm.v:105" *)
  always @(posedge clk)
      cand2_vote_recvd[7] <= _001_[7];
  (* src = "rtl/evm.v:105" *)
  always @(posedge clk)
      cand3_vote_recvd[0] <= _002_[0];
  (* src = "rtl/evm.v:105" *)
  always @(posedge clk)
      cand3_vote_recvd[1] <= _002_[1];
  (* src = "rtl/evm.v:105" *)
  always @(posedge clk)
      cand3_vote_recvd[2] <= _002_[2];
  (* src = "rtl/evm.v:105" *)
  always @(posedge clk)
      cand3_vote_recvd[3] <= _002_[3];
  (* src = "rtl/evm.v:105" *)
  always @(posedge clk)
      cand3_vote_recvd[4] <= _002_[4];
  (* src = "rtl/evm.v:105" *)
  always @(posedge clk)
      cand3_vote_recvd[5] <= _002_[5];
  (* src = "rtl/evm.v:105" *)
  always @(posedge clk)
      cand3_vote_recvd[6] <= _002_[6];
  (* src = "rtl/evm.v:105" *)
  always @(posedge clk)
      cand3_vote_recvd[7] <= _002_[7];
  (* src = "rtl/evm.v:105" *)
  always @(posedge clk)
      cand4_vote_recvd[0] <= _003_[0];
  (* src = "rtl/evm.v:105" *)
  always @(posedge clk)
      cand4_vote_recvd[1] <= _003_[1];
  (* src = "rtl/evm.v:105" *)
  always @(posedge clk)
      cand4_vote_recvd[2] <= _003_[2];
  (* src = "rtl/evm.v:105" *)
  always @(posedge clk)
      cand4_vote_recvd[3] <= _003_[3];
  (* src = "rtl/evm.v:105" *)
  always @(posedge clk)
      cand4_vote_recvd[4] <= _003_[4];
  (* src = "rtl/evm.v:105" *)
  always @(posedge clk)
      cand4_vote_recvd[5] <= _003_[5];
  (* src = "rtl/evm.v:105" *)
  always @(posedge clk)
      cand4_vote_recvd[6] <= _003_[6];
  (* src = "rtl/evm.v:105" *)
  always @(posedge clk)
      cand4_vote_recvd[7] <= _003_[7];
endmodule

(* top =  1  *)
(* src = "rtl/evm.v:127" *)
module votingMachine(clk, reset, mode, button1, button2, button3, button4, led);
  wire _0_;
  wire _1_;
  (* src = "rtl/evm.v:145" *)
  wire anyValidVote;
  (* src = "rtl/evm.v:131" *)
  input button1;
  (* src = "rtl/evm.v:132" *)
  input button2;
  (* src = "rtl/evm.v:133" *)
  input button3;
  (* src = "rtl/evm.v:134" *)
  input button4;
  (* src = "rtl/evm.v:141" *)
  wire [7:0] cand1_vote_recvd;
  (* src = "rtl/evm.v:142" *)
  wire [7:0] cand2_vote_recvd;
  (* src = "rtl/evm.v:143" *)
  wire [7:0] cand3_vote_recvd;
  (* src = "rtl/evm.v:144" *)
  wire [7:0] cand4_vote_recvd;
  (* src = "rtl/evm.v:128" *)
  input clk;
  (* src = "rtl/evm.v:135" *)
  output [7:0] led;
  (* src = "rtl/evm.v:130" *)
  input mode;
  (* src = "rtl/evm.v:129" *)
  input reset;
  (* src = "rtl/evm.v:137" *)
  wire valid_vote_1;
  (* src = "rtl/evm.v:138" *)
  wire valid_vote_2;
  (* src = "rtl/evm.v:139" *)
  wire valid_vote_3;
  (* src = "rtl/evm.v:140" *)
  wire valid_vote_4;
  assign _0_ = valid_vote_2 | valid_vote_1;
  assign _1_ = _0_ | valid_vote_3;
  assign anyValidVote = _1_ | valid_vote_4;
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/evm.v:191" *)
  modeControl MC (
    .cand1_button_press(valid_vote_1),
    .cand1_vote(cand1_vote_recvd),
    .cand2_button_press(valid_vote_2),
    .cand2_vote(cand2_vote_recvd),
    .cand3_button_press(valid_vote_3),
    .cand3_vote(cand3_vote_recvd),
    .cand4_button_press(valid_vote_4),
    .cand4_vote(cand4_vote_recvd),
    .clk(clk),
    .leds(led),
    .mode(mode),
    .reset(reset),
    .valid_vote_casted(anyValidVote)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/evm.v:177" *)
  voteLogger VL (
    .cand1_vote_recvd(cand1_vote_recvd),
    .cand1_vote_valid(valid_vote_1),
    .cand2_vote_recvd(cand2_vote_recvd),
    .cand2_vote_valid(valid_vote_2),
    .cand3_vote_recvd(cand3_vote_recvd),
    .cand3_vote_valid(valid_vote_3),
    .cand4_vote_recvd(cand4_vote_recvd),
    .cand4_vote_valid(valid_vote_4),
    .clk(clk),
    .mode(mode),
    .reset(reset)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/evm.v:149" *)
  buttonControl bc1 (
    .button(button1),
    .clk(clk),
    .reset(reset),
    .valid_vote(valid_vote_1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/evm.v:156" *)
  buttonControl bc2 (
    .button(button2),
    .clk(clk),
    .reset(reset),
    .valid_vote(valid_vote_2)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/evm.v:163" *)
  buttonControl bc3 (
    .button(button3),
    .clk(clk),
    .reset(reset),
    .valid_vote(valid_vote_3)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/evm.v:170" *)
  buttonControl bc4 (
    .button(button4),
    .clk(clk),
    .reset(reset),
    .valid_vote(valid_vote_4)
  );
endmodule
