/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "rtl/full_adder.v:23" *)
module full_adder(a, b, c, sum, carry);
  (* src = "rtl/full_adder.v:24" *)
  input a;
  (* src = "rtl/full_adder.v:24" *)
  input b;
  (* src = "rtl/full_adder.v:24" *)
  input c;
  (* src = "rtl/full_adder.v:25" *)
  output carry;
  (* src = "rtl/full_adder.v:25" *)
  output sum;
  (* src = "rtl/full_adder.v:26" *)
  wire w1;
  (* src = "rtl/full_adder.v:26" *)
  wire w2;
  (* src = "rtl/full_adder.v:26" *)
  wire w3;
  assign carry = w3 | w2;
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/full_adder.v:28" *)
  half_adder ha1 (
    .a(a),
    .b(b),
    .carry(w2),
    .sum(w1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/full_adder.v:29" *)
  half_adder ha2 (
    .a(w1),
    .b(c),
    .carry(w3),
    .sum(sum)
  );
endmodule

(* src = "rtl/full_adder.v:34" *)
module half_adder(a, b, sum, carry);
  (* src = "rtl/full_adder.v:35" *)
  input a;
  (* src = "rtl/full_adder.v:35" *)
  input b;
  (* src = "rtl/full_adder.v:36" *)
  output carry;
  (* src = "rtl/full_adder.v:36" *)
  output sum;
  assign sum = b ^ a;
  assign carry = b & a;
endmodule
