/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "rtl/half_adder.v:23" *)
module half_adder(a, b, sum, carry);
  (* src = "rtl/half_adder.v:24" *)
  input a;
  (* src = "rtl/half_adder.v:24" *)
  input b;
  (* src = "rtl/half_adder.v:25" *)
  output carry;
  (* src = "rtl/half_adder.v:25" *)
  output sum;
  assign sum = b ^ a;
  assign carry = b & a;
endmodule
