/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "rtl/jkff.v:23" *)
module jkff(jk, clk, q, qb);
  (* src = "rtl/jkff.v:28" *)
  wire _0_;
  wire _1_;
  (* src = "rtl/jkff.v:25" *)
  input clk;
  (* src = "rtl/jkff.v:24" *)
  input [1:0] jk;
  (* src = "rtl/jkff.v:26" *)
  output q;
  reg q;
  (* src = "rtl/jkff.v:26" *)
  output qb;
  assign _1_ = ~jk[0];
  assign _0_ = q ? _1_ : jk[1];
  assign qb = ~q;
  (* src = "rtl/jkff.v:28" *)
  always @(posedge clk)
      q <= _0_;
endmodule
