/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "rtl/MIPS.v:1" *)
module MIPS_32(clk1, clk2);
  (* src = "rtl/MIPS.v:20" *)
  wire HALTED;
  (* src = "rtl/MIPS.v:20" *)
  wire TAKEN_BRANCH;
  (* src = "rtl/MIPS.v:2" *)
  input clk1;
  (* src = "rtl/MIPS.v:2" *)
  input clk2;
  assign HALTED = 1'h1;
  assign TAKEN_BRANCH = 1'h0;
endmodule
