/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "rtl/mux2x1.v:23" *)
module mux2x1(a, b, sel, out);
  (* src = "rtl/mux2x1.v:24" *)
  input a;
  (* src = "rtl/mux2x1.v:24" *)
  input b;
  (* src = "rtl/mux2x1.v:25" *)
  output out;
  (* src = "rtl/mux2x1.v:24" *)
  input sel;
  assign out = sel ? b : a;
endmodule
