/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* src = "rtl/mux4x1.v:36" *)
module mux2x1(a, b, sel, out);
  (* src = "rtl/mux4x1.v:37" *)
  input a;
  (* src = "rtl/mux4x1.v:37" *)
  input b;
  (* src = "rtl/mux4x1.v:38" *)
  output out;
  (* src = "rtl/mux4x1.v:37" *)
  input sel;
  assign out = sel ? b : a;
endmodule

(* top =  1  *)
(* src = "rtl/mux4x1.v:23" *)
module mux4x1(a, b, c, d, sel, out);
  (* src = "rtl/mux4x1.v:24" *)
  input a;
  (* src = "rtl/mux4x1.v:24" *)
  input b;
  (* src = "rtl/mux4x1.v:24" *)
  input c;
  (* src = "rtl/mux4x1.v:24" *)
  input d;
  (* src = "rtl/mux4x1.v:26" *)
  output out;
  (* src = "rtl/mux4x1.v:25" *)
  input [1:0] sel;
  (* src = "rtl/mux4x1.v:31" *)
  wire w1;
  (* src = "rtl/mux4x1.v:29" *)
  wire w2;
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/mux4x1.v:31" *)
  mux2x1 u1 (
    .a(a),
    .b(b),
    .out(w1),
    .sel(sel[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/mux4x1.v:32" *)
  mux2x1 u2 (
    .a(c),
    .b(d),
    .out(w2),
    .sel(sel[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/mux4x1.v:33" *)
  mux2x1 u3 (
    .a(w1),
    .b(w2),
    .out(out),
    .sel(sel[1])
  );
endmodule
