/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "rtl/ring_counter.v:1" *)
module ring_counter(clk, init, count);
  (* src = "rtl/ring_counter.v:4" *)
  wire [7:0] _00_;
  (* src = "rtl/ring_counter.v:2" *)
  input clk;
  (* src = "rtl/ring_counter.v:3" *)
  output [7:0] count;
  reg [7:0] count;
  (* src = "rtl/ring_counter.v:2" *)
  input init;
  assign _00_[1] = count[0] & ~(init);
  assign _00_[2] = count[1] & ~(init);
  assign _00_[3] = count[2] & ~(init);
  assign _00_[4] = count[3] & ~(init);
  assign _00_[5] = count[4] & ~(init);
  assign _00_[6] = count[5] & ~(init);
  assign _00_[7] = count[6] | init;
  assign _00_[0] = count[7] & ~(init);
  (* src = "rtl/ring_counter.v:4" *)
  always @(posedge clk)
      count[0] <= _00_[0];
  (* src = "rtl/ring_counter.v:4" *)
  always @(posedge clk)
      count[1] <= _00_[1];
  (* src = "rtl/ring_counter.v:4" *)
  always @(posedge clk)
      count[2] <= _00_[2];
  (* src = "rtl/ring_counter.v:4" *)
  always @(posedge clk)
      count[3] <= _00_[3];
  (* src = "rtl/ring_counter.v:4" *)
  always @(posedge clk)
      count[4] <= _00_[4];
  (* src = "rtl/ring_counter.v:4" *)
  always @(posedge clk)
      count[5] <= _00_[5];
  (* src = "rtl/ring_counter.v:4" *)
  always @(posedge clk)
      count[6] <= _00_[6];
  (* src = "rtl/ring_counter.v:4" *)
  always @(posedge clk)
      count[7] <= _00_[7];
endmodule
