/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "rtl/seq_detector.v:2" *)
module seq_detector(x, clk, rst, z);
  wire _0_;
  wire _1_;
  wire _2_;
  (* onehot = 32'd1 *)
  (* unused_bits = "0" *)
  wire [3:0] PS;
  (* src = "rtl/seq_detector.v:3" *)
  input clk;
  (* src = "rtl/seq_detector.v:3" *)
  input rst;
  (* src = "rtl/seq_detector.v:3" *)
  input x;
  (* src = "rtl/seq_detector.v:4" *)
  output z;
  assign _2_ = ~x;
  assign _1_ = PS[1] & x;
  assign _0_ = PS[2] & x;
  assign z = PS[3] & ~(x);
  reg \PS_reg[1] ;
  always @(posedge clk or posedge rst)
    if (rst)
      \PS_reg[1]  <= 0;
    else
      \PS_reg[1]  <= _0_;
  assign PS[1] = \PS_reg[1] ;
  reg \PS_reg[2] ;
  always @(posedge clk or posedge rst)
    if (rst)
      \PS_reg[2]  <= 0;
    else
      \PS_reg[2]  <= _2_;
  assign PS[2] = \PS_reg[2] ;
  reg \PS_reg[3] ;
  always @(posedge clk or posedge rst)
    if (rst)
      \PS_reg[3]  <= 0;
    else
      \PS_reg[3]  <= _1_;
  assign PS[3] = \PS_reg[3] ;
endmodule
