/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "rtl/srff.v:22" *)
module srff(sr, clk, q, qb);
  (* src = "rtl/srff.v:28" *)
  wire _0_;
  wire _1_;
  wire _2_;
  (* src = "rtl/srff.v:24" *)
  input clk;
  (* src = "rtl/srff.v:25" *)
  output q;
  reg q;
  (* src = "rtl/srff.v:25" *)
  output qb;
  (* src = "rtl/srff.v:23" *)
  input [1:0] sr;
  assign qb = ~q;
  assign _1_ = sr[1] ^ sr[0];
  assign _2_ = sr[0] | ~(sr[1]);
  assign _0_ = ~((_1_ | qb) & _2_);
  (* src = "rtl/srff.v:28" *)
  always @(posedge clk)
      q <= _0_;
endmodule
