/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "rtl/tff.v:23" *)
module tff(t, clk, q, qb);
  (* src = "rtl/tff.v:28" *)
  wire _0_;
  (* src = "rtl/tff.v:24" *)
  input clk;
  (* init = 1'h0 *)
  (* src = "rtl/tff.v:25" *)
  output q;
  reg q = 1'h0;
  (* src = "rtl/tff.v:25" *)
  output qb;
  (* src = "rtl/tff.v:24" *)
  input t;
  assign qb = ~q;
  assign _0_ = t ^ q;
  (* src = "rtl/tff.v:28" *)
  always @(posedge clk)
      q <= _0_;
endmodule
