/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "rtl/traffic_light_controller.v:3" *)
module traffic_light_controller(clk, rst, light_M1, light_S, light_MT, light_M2);
  (* src = "rtl/traffic_light_controller.v:19" *)
  wire [3:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  (* src = "rtl/traffic_light_controller.v:5" *)
  input clk;
  (* src = "rtl/traffic_light_controller.v:13" *)
  reg [3:0] count;
  (* src = "rtl/traffic_light_controller.v:6" *)
  output [2:0] light_M1;
  (* src = "rtl/traffic_light_controller.v:9" *)
  output [2:0] light_M2;
  (* src = "rtl/traffic_light_controller.v:8" *)
  output [2:0] light_MT;
  (* src = "rtl/traffic_light_controller.v:7" *)
  output [2:0] light_S;
  (* onehot = 32'd1 *)
  reg [5:0] ps;
  (* src = "rtl/traffic_light_controller.v:5" *)
  input rst;
  assign _037_ = ~ps[0];
  assign _038_ = ~ps[4];
  assign _039_ = ~count[1];
  assign _040_ = ~(count[3] | count[2]);
  assign _041_ = count[1] & ~(count[0]);
  assign _042_ = ~((_041_ | _039_) & _040_);
  assign _043_ = count[3] | count[2];
  assign _044_ = _041_ & ~(_043_);
  assign _045_ = _044_ | _042_;
  assign _046_ = ~_045_;
  assign _047_ = count[3] | ~(count[2]);
  assign _048_ = count[1] & count[0];
  assign _049_ = _047_ ? _043_ : _048_;
  assign _001_ = ~((_049_ | _037_) & (_046_ | _038_));
  assign _050_ = ~ps[3];
  assign _051_ = ~(_049_ & ps[0]);
  assign _004_ = ~((_045_ | _050_) & _051_);
  assign _052_ = ~ps[2];
  assign _053_ = ~((count[2] & count[1]) | count[3]);
  assign _054_ = count[1] | ~(count[0]);
  assign _055_ = ~((_054_ | _047_) & _053_);
  assign _003_ = ~((_055_ | _052_) & (_046_ | _050_));
  assign _056_ = ~ps[5];
  assign _057_ = ~(_055_ & ps[2]);
  assign _006_ = ~((_045_ | _056_) & _057_);
  assign _058_ = ~ps[1];
  assign _059_ = _048_ | _043_;
  assign _002_ = ~((_059_ | _058_) & (_046_ | _056_));
  assign _060_ = ~(_059_ & ps[1]);
  assign _005_ = ~((_045_ | _038_) & _060_);
  assign _061_ = ~(ps[1] | ps[4]);
  assign _062_ = ~(ps[5] | ps[3]);
  assign _063_ = ~(ps[0] | ps[2]);
  assign _064_ = ~(_063_ & _062_);
  assign _065_ = _061_ & ~(_064_);
  assign light_S[0] = ps[1] & ~(_065_);
  assign light_S[1] = ps[4] & ~(_065_);
  assign light_S[2] = _064_ & ~(_065_);
  assign _066_ = ps[2] | ps[3];
  assign _067_ = _061_ & ~(ps[5]);
  assign light_M1[0] = _066_ | ps[0];
  assign _068_ = _037_ & ~(_066_);
  assign _069_ = _067_ & _068_;
  assign light_M1[1] = ps[5] & ~(_069_);
  assign light_M1[2] = ~(_069_ | _061_);
  assign _070_ = ps[4] | ps[5];
  assign _071_ = ps[1] | ps[2];
  assign _072_ = _071_ | _070_;
  assign _073_ = _050_ & ~(_072_);
  assign _074_ = _073_ & ~(ps[0]);
  assign light_M2[0] = ps[0] & ~(_074_);
  assign light_M2[1] = ps[3] & ~(_074_);
  assign light_M2[2] = _072_ & ~(_074_);
  assign _075_ = ps[4] | ps[3];
  assign _076_ = ps[1] | ps[0];
  assign _077_ = _076_ | _075_;
  assign _078_ = _056_ & ~(_077_);
  assign _079_ = _078_ & ~(ps[2]);
  assign light_MT[0] = ps[2] & ~(_079_);
  assign light_MT[1] = ps[5] & ~(_079_);
  assign light_MT[2] = _077_ & ~(_079_);
  assign _080_ = _050_ & ~(_070_);
  assign _081_ = ~(_080_ & _058_);
  assign _082_ = _063_ & ~(_081_);
  assign _083_ = _045_ | count[0];
  assign _084_ = _059_ | count[0];
  assign _085_ = ~((_084_ | _058_) & (_083_ | _080_));
  assign _007_ = _055_ | count[0];
  assign _008_ = _049_ | count[0];
  assign _009_ = ~((_008_ | _037_) & (_007_ | _052_));
  assign _010_ = _009_ | _085_;
  assign _000_[0] = _082_ ? count[0] : _010_;
  assign _011_ = _054_ & ~(_041_);
  assign _012_ = _011_ | _045_;
  assign _013_ = _011_ | _059_;
  assign _014_ = ~((_013_ | _058_) & (_012_ | _080_));
  assign _015_ = _011_ | _055_;
  assign _016_ = _011_ | _049_;
  assign _017_ = ~((_016_ | _037_) & (_015_ | _052_));
  assign _018_ = _017_ | _014_;
  assign _000_[1] = _082_ ? count[1] : _018_;
  assign _019_ = ~(count[1] & count[0]);
  assign _020_ = _019_ ^ count[2];
  assign _021_ = _020_ | _045_;
  assign _022_ = _020_ | _059_;
  assign _023_ = ~((_022_ | _058_) & (_021_ | _080_));
  assign _024_ = _020_ | _055_;
  assign _025_ = _020_ | _049_;
  assign _026_ = ~((_025_ | _037_) & (_024_ | _052_));
  assign _027_ = _026_ | _023_;
  assign _000_[2] = _082_ ? count[2] : _027_;
  assign _028_ = ~(_048_ & count[2]);
  assign _029_ = _028_ ^ count[3];
  assign _030_ = _029_ | _045_;
  assign _031_ = _029_ | _059_;
  assign _032_ = ~((_031_ | _058_) & (_030_ | _080_));
  assign _033_ = _029_ | _055_;
  assign _034_ = _029_ | _049_;
  assign _035_ = ~((_034_ | _037_) & (_033_ | _052_));
  assign _036_ = _035_ | _032_;
  assign _000_[3] = _082_ ? count[3] : _036_;
  always @(posedge clk or posedge rst)
    if (rst)
      ps[0] <= 1;
    else
      ps[0] <= _001_;
  always @(posedge clk or posedge rst)
    if (rst)
      ps[1] <= 0;
    else
      ps[1] <= _002_;
  always @(posedge clk or posedge rst)
    if (rst)
      ps[2] <= 0;
    else
      ps[2] <= _003_;
  always @(posedge clk or posedge rst)
    if (rst)
      ps[3] <= 0;
    else
      ps[3] <= _004_;
  always @(posedge clk or posedge rst)
    if (rst)
      ps[4] <= 0;
    else
      ps[4] <= _005_;
  always @(posedge clk or posedge rst)
    if (rst)
      ps[5] <= 0;
    else
      ps[5] <= _006_;
  (* src = "rtl/traffic_light_controller.v:19" *)
  always @(posedge clk or posedge rst)
    if (rst)
      count[0] <= 0;
    else
      count[0] <= _000_[0];
  (* src = "rtl/traffic_light_controller.v:19" *)
  always @(posedge clk or posedge rst)
    if (rst)
      count[1] <= 0;
    else
      count[1] <= _000_[1];
  (* src = "rtl/traffic_light_controller.v:19" *)
  always @(posedge clk or posedge rst)
    if (rst)
      count[2] <= 0;
    else
      count[2] <= _000_[2];
  (* src = "rtl/traffic_light_controller.v:19" *)
  always @(posedge clk or posedge rst)
    if (rst)
      count[3] <= 0;
    else
      count[3] <= _000_[3];
endmodule
