/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "rtl/vm.v:3" *)
module vm(clk, reset, in, out, change);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  (* onehot = 32'd1 *)
  reg [2:0] c_state;
  (* src = "rtl/vm.v:8" *)
  output [1:0] change;
  (* src = "rtl/vm.v:4" *)
  input clk;
  (* src = "rtl/vm.v:6" *)
  input [1:0] in;
  (* src = "rtl/vm.v:7" *)
  output out;
  (* src = "rtl/vm.v:5" *)
  input reset;
  assign _03_ = ~c_state[2];
  assign _04_ = ~c_state[1];
  assign _05_ = in[1] | ~(in[0]);
  assign _06_ = ~(in[0] & in[1]);
  assign _07_ = ~((_06_ | _04_) & (_05_ | _03_));
  assign _08_ = in[0] | ~(in[1]);
  assign _09_ = c_state[0] & ~(_08_);
  assign _01_ = _09_ | _07_;
  assign _10_ = ~c_state[0];
  assign _02_ = ~((_06_ | _03_) & (_05_ | _10_));
  assign _11_ = in[0] | in[1];
  assign _12_ = ~((_06_ | _10_) & _11_);
  assign _13_ = ~(c_state[1] | c_state[2]);
  assign _14_ = ~((_13_ | _08_) & (_05_ | _04_));
  assign _00_ = _14_ | _12_;
  assign change[0] = ~((_08_ | _04_) & (_11_ | _03_));
  assign _15_ = ~(in[0] ^ in[1]);
  assign out = ~((_15_ | _04_) & (_08_ | _03_));
  always @(posedge clk or posedge reset)
    if (reset)
      c_state[0] <= 1;
    else
      c_state[0] <= _00_;
  always @(posedge clk or posedge reset)
    if (reset)
      c_state[1] <= 0;
    else
      c_state[1] <= _01_;
  always @(posedge clk or posedge reset)
    if (reset)
      c_state[2] <= 0;
    else
      c_state[2] <= _02_;
  assign change[1] = 1'h0;
endmodule
